version: '2'
services:

  ### MySql container
  mysql:
    container_name: "mysqlserver"
    image: mysql:latest
    ports:
      - "8000:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: lyrics
       MYSQL_USER: user1
       MYSQL_PASSWORD: password1
       MYSQL_ROOT_HOST: '%'
